name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Init gcloud
        run: |
          echo "${{ secrets.GCLOUD_KEY }}" | base64 -d > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Build
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks.json
        run: |
          yarn
          yarn build

      - name: Upload
        run: gsutil -m rsync -r -d ./build gs://spacemesh-explorer

      - name: Remove build dir
        run: rm -rf ./build

      - name: Build dev
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks-dev.json
          PUBLIC_URL: /spacemesh-explorer-dev/
        run: |
          yarn
          yarn build

      - name: Upload dev
        run: gsutil -m rsync -r -d ./build gs://spacemesh-explorer-dev
