name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud authentication
        uses: google-github-actions/auth@v2
        id: 'auth'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: access_token

      - name: Build to Mainnet Explorer
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks.json
          REACT_APP_LABELS_PER_UNIT: 4294967296
        run: |
          yarn
          yarn build

      - name: Upload to Mainnet Explorer
        run: gsutil -m rsync -r -d ./build gs://spacemesh-explorer

      - name: Set cache-control headers for Mainnet Explorer
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=0, no-transform" -r gs://spacemesh-explorer/index.html

      - name: Remove build dir
        run: rm -rf ./build

      - name: Build to Dev Explorer
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks-dev.json
          REACT_APP_LABELS_PER_UNIT: 1024
        run: |
          yarn
          yarn build

      - name: Upload to Dev Explorer
        run: gsutil -m rsync -r -d ./build gs://explorer-dev.spacemesh.network

      - name: Set cache-control headers for Dev Explorer
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=0, no-transform" -r gs://explorer-dev.spacemesh.network/index.html
