name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Init gcloud
        run: |
          echo "${{ secrets.GCLOUD_KEY }}" | base64 -d > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Build to Mainnet Explorer
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks.json
        run: |
          yarn
          yarn build

      - name: Upload to Mainnet Explorer
        run: gsutil -m rsync -r -d ./build gs://spacemesh-explorer

      - name: Remove build dir
        run: rm -rf ./build

      - name: Build to Dev Explorer
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks-dev.json
          PUBLIC_URL: /spacemesh-explorer-dev/
        run: |
          yarn
          yarn build

      - name: Upload to Dev Explorer
        run: gsutil -m rsync -r -d ./build gs://spacemesh-explorer-dev

      - name: Build to testnet-15 Explorer
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks-testnet-15.json
        run: |
          yarn
          yarn build

      - name: Upload to testnet-15 Explorer
        run: gsutil -m rsync -r -d ./build gs://testnet-15-explorer.spacemesh.network

      - name: Build to testnet-atxmerge2 Explorer
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks-testnet-atxmerge2.json
        run: |
          yarn
          yarn build
      
      - name: Upload to testnet-atxmerge2 Explorer
        run: gsutil -m rsync -r -d ./build gs://testnet-atxmerge2-explorer.spacemesh.network
      
      - name: Build to testnet-atxmerge3 Explorer
        env:
          REACT_APP_DISCOVERY_SERVICE_URL: https://configs.spacemesh.network/networks-testnet-atxmerge3.json
        run: |
          yarn
          yarn build
      
      - name: Upload to testnet-atxmerge3 Explorer
        run: gsutil -m rsync -r -d ./build gs://testnet-atxmerge3-explorer.spacemesh.network
